import = ["/home/jadebetty/.config/alacritty/themes/themes/gruvbox_dark.yaml"]

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1d202f"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[schemes.indexed_colors]]
color = "#FAB387"
index = 16

[[schemes.indexed_colors]]
color = "#F5E0DC"
index = 17

[[schemes.CatppuccinMacchiato.indexed_colors]]
color = "#F5A97F"
index = 16

[[schemes.CatppuccinMacchiato.indexed_colors]]
color = "#F4DBD6"
index = 17

[schemes.CatppuccinMacchiato.bright]
black = "#5B6078"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#A5ADCB"
yellow = "#EED49F"

[schemes.CatppuccinMacchiato.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[schemes.CatppuccinMacchiato.dim]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[schemes.CatppuccinMacchiato.hints.end]
background = "#A5ADCB"
foreground = "#24273A"

[schemes.CatppuccinMacchiato.hints.start]
background = "#EED49F"
foreground = "#24273A"

[schemes.CatppuccinMacchiato.normal]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[schemes.CatppuccinMacchiato.primary]
background = "#24273A"
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
foreground = "#CAD3F5"

[schemes.CatppuccinMacchiato.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"

[schemes.CatppuccinMacchiato.search.footer_bar]
background = "#A5ADCB"
foreground = "#24273A"

[schemes.CatppuccinMacchiato.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[schemes.CatppuccinMacchiato.selection]
background = "#F4DBD6"
text = "#24273A"

[schemes.CatppuccinMacchiato.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"

[schemes.CatppuccinMocha.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[schemes.DoomOne.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[schemes.DoomOne.cursor]
cursor = "#528bff"
text = "CellBackground"

[schemes.DoomOne.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#202328"
yellow = "#da8548"

[schemes.DoomOne.primary]
background = "#282c34"
foreground = "#bbc2cf"

[schemes.DoomOne.selection]
background = "#3e4451"
text = "CellForeground"

[schemes.Dracula.bright]
black = "#4d4d4d"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[schemes.Dracula.cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.Dracula.dim]
black = "#14151b"
blue = "#4d5b86"
cyan = "#59dffc"
green = "#1ef956"
magenta = "#ff46b0"
red = "#ff2222"
white = "#e6e6d1"
yellow = "#ebf85b"

[schemes.Dracula.line_indicator]
background = "None"
foreground = "None"

[schemes.Dracula.normal]
black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[schemes.Dracula.primary]
background = "#282a36"
foreground = "#f8f8f2"

[schemes.Dracula.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[schemes.Dracula.search.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[schemes.Dracula.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[schemes.Dracula.selection]
background = "#44475a"
text = "CellForeground"

[schemes.Dracula.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.GruvboxDark.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[schemes.GruvboxDark.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[schemes.GruvboxDark.primary]
background = "#282828"
foreground = "#ebdbb2"

[schemes.MonokaiPro.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.MonokaiPro.normal]
black = "#403E41"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.MonokaiPro.primary]
background = "#2D2A2E"
foreground = "#FCFCFA"

[schemes.Nord.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[schemes.Nord.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[schemes.Nord.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[schemes.OceanicNext.bright]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[schemes.OceanicNext.cursor]
cursor = "#ffffff"
text = "#1b2b34"

[schemes.OceanicNext.normal]
black = "#343d46"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99C794"
magenta = "#c594c5"
red = "#EC5f67"
white = "#d8dee9"
yellow = "#FAC863"

[schemes.OceanicNext.primary]
background = "#1b2b34"
foreground = "#d8dee9"

[schemes.OneDark.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.OneDark.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[schemes.OneDark.primary]
background = "#282c34"
foreground = "#abb2bf"

[schemes.OneDark.selection]
background = "#3e4451"
text = "CellForeground"

[schemes.OneDark.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.OneDarkMod.bright]
black = "#1e2127"
blue = "#6eaafb"
cyan = "#6cdcf7"
green = "#95ee8f"
magenta = "#d886f3"
red = "#eb6e67"
white = "#b2b2b2"
yellow = "#f8c456"

[schemes.OneDarkMod.dim]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828791"
yellow = "#d19a66"

[schemes.OneDarkMod.normal]
black = "#50536b"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "#dfdfdf"
yellow = "0xd19a66"

[schemes.OneDarkMod.primary]
background = "#1e2127"
bright_foreground = "0xe6efff"
foreground = "#abb2bf"

[schemes.Palenight.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#e1acff"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[schemes.Palenight.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#d0d0d0"
yellow = "#ffcb6b"

[schemes.Palenight.primary]
background = "#292d3e"
foreground = "#d0d0d0"

[schemes.SolarizedDark.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.SolarizedDark.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.SolarizedDark.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.SolarizedDark.primary]
background = "#002b36"
foreground = "#839496"

[schemes.SolarizedLight.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.SolarizedLight.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[schemes.SolarizedLight.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.SolarizedLight.primary]
background = "#fdf6e3"
foreground = "#657b83"

[[schemes.Tokyonight.indexed_colors]]
color = "0xb15c00"
index = 16

[[schemes.Tokyonight.indexed_colors]]
color = "0xc64343"
index = 17

[schemes.Tokyonight.bright]
black = "0xa1a6c5"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x3760bf"
yellow = "0x8c6c3e"

[schemes.Tokyonight.normal]
black = "0xe9e9ed"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x6172b0"
yellow = "0x8c6c3e"

[schemes.Tokyonight.primary]
background = "0xe1e2e7"
foreground = "0x3760bf"

[[schemes.TokyonightStorm.indexed_colors]]
color = "0xff9e64"
index = 16

[[schemes.TokyonightStorm.indexed_colors]]
color = "0xdb4b4b"
index = 17

[schemes.TokyonightStorm.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[schemes.TokyonightStorm.normal]
black = "0x1d202f"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[schemes.TokyonightStorm.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[schemes.TomorrowNight.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#282a2e"
yellow = "#f0c674"

[schemes.TomorrowNight.cursor]
cursor = "#ffffff"
text = "#1d1f21"

[schemes.TomorrowNight.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[schemes.TomorrowNight.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[schemes.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[schemes.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[schemes.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[schemes.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[schemes.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[schemes.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[schemes.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[schemes.search.footer_bar]
background = "#A6ADC8"
foreground = "#1E1E2E"

[schemes.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[schemes.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[schemes.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[window]
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 6
